ifeq ($(mode),release)
	CFLAGS = -O3 -g0
	OUT="./bin/libmod_mingw32.a"
else
	mode = debug
	CFLAGS = -O0 -g3
	OUT="./bin/libmod_d_mingw32.a"
endif

-include ./src/Makefile.Mingw32

all: cleanobjs $(OBJS)
	@echo 'Building target: $@'
	@echo 'Invoking: GCC Archiver'
	ar -r $(OUT) $(OBJS)
	@echo 'Finished building target: $@'
	@echo ' '

cleanobjs:
	rm -rf $(OBJS)
	@echo ' '

clean:
	rm -rf $(OBJS)$(C_DEPS) ./bin/libmod_d_mingw32.a ./bin/libmod_mingw32.a
	@echo ' '

.PHONY: all clean
