OUT=../bin/module.lmm

-include ./src/Makefile.Linux

all: cleanobjs $(OBJS)
	@echo 'Building target: $@'
	@echo 'Invoking: GCC C Compiler'
	gcc $(OBJS) -shared -o $(OUT) -L../../../bin -lmod_d_linux
	@echo 'Finished building target: $@'
	@echo ' '

cleanobjs:
	rm -rf $(OBJS)
	@echo ' '

clean:
	rm -rf $(OBJS)$(C_DEPS) $(OUT)
	@echo ' '

.PHONY: all clean
