OUT=../bin/application

-include ./src/Mingw32.Linux

all: cleanobjs $(OBJS)
	@echo 'Building target: $@'
	@echo 'Invoking: GCC C Compiler'
	gcc $(OBJS) -o $(OUT) -L../../../bin -lmod_d_mingw32 -ldl
	@echo 'Finished building target: $@'
	@echo ' '

cleanobjs:
	rm -rf $(OBJS)
	@echo ' '

clean:
	rm -rf $(OBJS)$(C_DEPS) $(OUT)
	@echo ' '

.PHONY: all clean
